<?php
$name = $_POST["name"];
$email = $_POST["email"];
$mobile = $_POST["mobile"];
$linkedin = $_POST["linkedin"];
$gender = $_POST["gender"];
$subject = $_POST["subject"];

ini_set('display_errors', 1);
require_once('PHPMailer/class.phpmailer.php');
require_once('PHPMailer/class.smtp.php');
$mail = new PHPMailer();
$mail->isSMTP();
$mail->SMTPAuth = true;
$mail->SMTPSecure = 'ssl';
$mail->Host = 'smtp.gmail.com';
$mail->Port = '465';
$mail->isHTML();
/*Mandatorily fill the sender email address [eg: jithendra.vivek@gmail.com]*/
$mail->Username = 'jithendra.vivek@gmail.com';
/*Mandatorily fill the sender email password [eg: mypassword]*/
$mail->Password = '';
$mail->SetFrom('no-reply@zap.com');
$mail->Subject = 'Welcome to Zap';
$mail->Body = "Hi ".$name.",<br> Welcome to zap. Thank you for joining us. Below are the details you gave us.<br><br>Name : " .$name. ".<br>E-mail : " .$email. ".<br>Mobile : " .$mobile. ".<br>LinkedIn : " .$linkedin. ".<br>Gender : " .$gender. ".<br>Subject : " .$subject. "." ;
$mail->AddAddress($email);
$mail->Send();
$mail->ClearAllRecipients();
$mail->Subject = "".$name." wants to connect with zap";
$mail->Body = "Hi Team Zap,<br> A new customer wants to join us. Below are his/her details.<br><br>Name : " .$name. ".<br>E-mail : " .$email. ".<br>Mobile : " .$mobile. ".<br>LinkedIn : " .$linkedin. ".<br>Gender : " .$gender. ".<br>Subject : " .$subject. "." ;
/*Mandatorily fill the company receiver email address [eg: jithendra.vivek@gmail.com]*/
$mail->AddAddress('jithendra.vivek@gmail.com');
$mail->Send();
?>

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Mailer</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	<script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
	<link href="style.css" rel="stylesheet">
</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
<div class="container-fluid">
	<a class="navbar-brand text-primary font-weight-bold" href="#">Mailer</a>
</div>	
</nav>
<!-- End Navigation -->

<br><br>

<!--Join Us Form-->
<div class="container-fluid padding">
<div class="row welcome text-center">
	<div class="col-12">
		<h1 class="display-4">Congratulations.!</h1>
<hr width="150px">
	</div>
	<div class="col-12">
		<p class="lead">You successfully joined us. We will be in touch with you.<br>We also dropped an email to your inbox please verify your details.</p>
	</div>
</div>
</div>
<!--End Join Us Form-->

</body>
</html>
